# Generated by Django 3.0.5 on 2020-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('user_id', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.CharField(max_length=250, unique=True)),
                ('coupon', models.CharField(max_length=250, null=True)),
                ('birth', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('kakao_id', models.IntegerField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
